global:
  resolve_timeout: 5m

route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: ja.zon257@gmail.com
    from: ja.zon257@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "ja.zon257@gmail.com"
    auth_identity: "ja.zon257@gmail.com"
    auth_password: ""