global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
    scheme: http
    timeout: 10s

rule_files:
  - "/alertmanager/alert.rules/alerts.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']

    file_sd_configs:
      - files:
        - '/etc/prometheus/file_sd_configs.yml'

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['127.0.0.1:8080']

    file_sd_configs:
      - files:
        - '/etc/prometheus/file_sd_configs.yml'